import {
	IE_GRIME_LEVEL,
	IE_IMMEDIATE,
	IE_LOCATION,
	IE_SYNDROME_TAG,
	IE_TARGET,
	INTERACTION,
	IT_LOCATION,
	IT_MANUAL_INPUT,
	IT_MATERIAL,
	I_EFFECT,
	I_SOURCE,
	I_TARGET
} from '../generatedDefinitions';
import {
	IS_HIST_STRING_1,
	IS_HIST_STRING_2,
	IS_FREQUENCY,
	IS_NAME,
	IS_REGION,
	IS_SPHERE,
	IS_SECRET_GOAL,
	IS_SECRET,
	IS_USAGE_HINT,
	IT_AFFECTED_CREATURE,
	IT_AFFECTED_CLASS,
	IT_IMMUNE_CREATURE,
	IT_IMMUNE_CLASS,
	IT_REQUIRES,
	IT_FORBIDDEN,
	IT_CANNOT_TARGET_IF_ALREADY_AFFECTED,
	IT_CANNOT_HAVE_SYNDROME_CLASS,
	IE_INTERMITTENT,
	IE_ARENA_NAME
} from '../undeliveredDefinitions';
import {withChildren} from '../definitionUtils';

export default withChildren(INTERACTION, [
	withChildren(I_SOURCE, [
		IS_HIST_STRING_1,
		IS_HIST_STRING_2,
		IS_FREQUENCY,
		IS_NAME,
		IS_REGION,
		IS_SPHERE,
		IS_SECRET_GOAL,
		IS_SECRET,
		IS_USAGE_HINT
	]),
	withChildren(I_TARGET, [
		IT_LOCATION,
		IT_MANUAL_INPUT,
		IT_AFFECTED_CREATURE,
		IT_AFFECTED_CLASS,
		IT_IMMUNE_CREATURE,
		IT_IMMUNE_CLASS,
		IT_REQUIRES,
		IT_FORBIDDEN,
		IT_CANNOT_TARGET_IF_ALREADY_AFFECTED,
		IT_CANNOT_HAVE_SYNDROME_CLASS,
		IT_MATERIAL
	]),
	withChildren(I_EFFECT, [
		IE_TARGET,
		IE_INTERMITTENT,
		IE_IMMEDIATE,
		IE_LOCATION,
		IE_ARENA_NAME,
		IE_GRIME_LEVEL,
		IE_SYNDROME_TAG
	])
]);
